# Font
font_family      FiraCode Nerd Font
font_size 10

hide_window_decorations yes
# Cursor
cursor #ff4fa3
cursor_blink_interval 0.5
cursor_trail 3
scrollback_lines -1

# Terminal bell
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no

# Layout
window_margin_width 5
confirm_os_window_close 0

# Color
#foreground #c0caf5
#foreground #65c3b2
#background #18192a
#background #1a1b26 #tooop
background #282828
foreground #ebdbb2
selection-background = #2a2a2a
selection-foreground = #f2f4f8

background_opacity 0.9
dynamic_background_opacity   yes

# shell
shell zsh

# Keys
kitty_mod alt

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map kitty_mod+k       scroll_line_up
map kitty_mod+j       scroll_line_down


map kitty_mod+equal       change_font_size all +1.0
map kitty_mod+minus       change_font_size all -1.0


map kitty_mod+ctrl+equal set_background_opacity +0.05
map kitty_mod+ctrl+minus set_background_opacity -0.05

color0 #15161e
color8 #65c3b2

color1 #f7768e
color9 #f7768e

color2 #a6ff00
color10 #a6ff00

color3 #e0af68
color11 #e0af68

color4 #7aa2f7
color12 #7aa2f7

color5 #ff4fa3
color13 #ff4fa3

color6 #7dcfff
color14 #7dcfff

color7 #a9b1d6
color15 #a9b1d6



color0 #282828
color8 #928374

color1 #cc241d
color9 #fb4934

color2 #98971a
color10 #b8bb26

color3 #d79921
color11 #fabd2f

color4 #458588
color12 #83a598

color5 #b16286
color13 #d3869b

color6 #689d6a
color14 #8ec07c

color7 #a89984
color15 #ebdbb2
