$text_color = rgba(fabd2fFF)

$entry_background_color = rgba(282828CC)
$entry_border_color = rgba(b8bb26FF)
$entry_color = rgba(83a598FF)

$font_family = BigBlueTermPlus Nerd Font
$font_family_clock = BigBlueTermPlus Nerd Font
$ATTEMPTS = 10


general {
    ignore_empty_input = true
    text_trim = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 3
}


input-field {
    monitor =
    size = 350, 80
    outline_thickness = 4
    dots_size = 0.1
    dots_spacing = 0.45
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    font_color = $entry_color

    position = 0, -350
    halign = center
    valign = center
}

label { # Layout
    monitor =
    text = $LAYOUT
    color = $text_color
    font_size = 18
    font_family = $font_family
    position = -30, 30
    halign = right
    valign = bottom
}


label { # Clock
    monitor =
    text = $TIME
    color = $text_color
    font_size = 300
    font_family = $font_family_clock

    position = 0, 0
    halign = center
    valign = center
}
#label { # Date
#    monitor =
#    text = cmd[update:5000] date +"%A, %d %B"
#    color = $text_color
#    font_size = 17
#    font_family = $font_family_clock

#    position = 0, 240
#    halign = center
#    valign = center
#}

label { # User
    monitor =
    text =   $USER
    color = $text_color
    outline_thickness = 2
    dots_size = 0
    dots_spacing = 0
    dots_center = true
    font_size = 25
    font_family = $font_family
    position = 0, 50
    halign = center
    valign = bottom
}

label { # Caps
    monitor =
    text = cmd[update:200] echo "$(~/.config/hypr/scripts/caps.sh)"
    color = $text_color
    font_size = 19
    font_family = $font_family

    position = 0, -280
    halign = center
    valign = center
}
