$lock_cmd = niri msg action-quickshell-lock || hyprlock # Пример для блокировки
$suspend_cmd = systemctl hibernate

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    # after_sleep_cmd у niri обычно не требует принудительного focus-lock через hyprctl
    inhibit_sleep = 3
}

listener {
    timeout = 420 # 7мин
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600 # 10мин
    # Команды управления монитором изменены на niri msg
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# listener {
#    timeout = 1500 # 25мин
#    on-timeout = $suspend_cmd
# }

